/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package analisador_lexico;
import analisador_lexico.grammar.*;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.Token;

import java.sql.SQLOutput;

public class App {

    private static final String FILE_LOCATION = "src/main/antlr/files/programaSoma.minip";

    public static void main(String[] args) {
        try {
            CharStream charStreams = CharStreams.fromFileName(FILE_LOCATION);

            AnLexer lexer = new AnLexer(charStreams);
            Token t = null;


            while ((t = lexer.nextToken()).getType() != Token.EOF){
                System.out.println("Reconhecido: " + lexer.getText() + "," + lexer.getToken());
                System.out.println("<TOKEN, ENTRADA>: <" + lexer.VOCABULARY.getDisplayName(t.getType()) + "," + t.getText() + ">");
                System.out.println("");
            }

        } catch (Exception e){
            System.out.println("ERROR");
            System.out.println(e.getMessage());
        }

    }
}
